### PR TITLE
Point to new production endpoint

### PR DESCRIPTION
**Pull request by mojodna**
Numbers will differ, user extents will be empty.

### CODE REVIEW

**Comment by dalekunce** [comment]
User heat map doesn't work. If the map of edits is to much, maybe just make a chloroplath based on the numbers from the API. I think this would be the least amount of new work.

screen shot 2018-03-21 at 6 20 37 pm

**Comment by dalekunce** [comment]
I don't all the badge workers are working, specifically the GPS traces and any badges that have to do with the TM. TM badges could be because of the migration to TM3.

http://192.168.0.3:9966/#/dkunce/badges

screen shot 2018-03-21 at 6 41 40 pm

**Comment by mojodna** [comment]
The user heatmap hasn't worked properly for a long time. If it did, the geometries stored would have been enormous (element shapes were buffered and unioned with the existing user extent) with a correspondingly large response. A choropleth would be an excellent alternative.

Country numbers are the number of changesets that a user has contributed that touch a given country.

Most of the code related to GPS traces I'd seen was commented out (none of the values were being updated so I suspect that they were only active early on). I don't see a particularly feasible solution for resurrecting these, since we don't have a mechanism for fetching trace counts in bulk (we'd need to query each user individually (and periodically), and we're now storing stats for _all_ users).

TM badges haven't updated since TM3 was deployed. See the HOT Slack for discussion about getting a new endpoint that can be used to seed updates.

**Comment by dalekunce** [comment]
Lets role the choropleth and call it a day for the map.

Lets drop the GPS trace badge, its really old school anyway.

Fingers crossed the TM3 conversation yields the stuff we need.

**Comment by mojodna** [comment]
GPS traces dropped here and in osm-stats-workers.

Choropleth:

image

**Comment by dalekunce** [comment]
@mojodna the TM stuff isn't likely to get resolved tomorrow? Lets go ahead and merge then and file an issue to take care of that when/if the TM stuff gets fixed.

**Comment by mojodna** [comment]
Hopefully next week. I'll go ahead and merge stuff.

**Pull request merged**
