### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by dalekunce** [comment]
@pgiraud can you do this against the publish branch. We then use Travis to build the master branch.

**Comment by dalekunce** [comment]
ignore me. I wasn't paying attention that this was in the user branch. Can you resubmit your PR and I'll merge properly this time.

**Comment by pgiraud** [comment]
I'm a bit confused. You're talking about the "MissingMaps/users" project right?
Should I create a pull request against the master branch of this project?

**Comment by dalekunce** [comment]
sorry @pgiraud thats what I get for trying to merge PRs from bed :)

resubmit the PR as you did initially and it should be good to go.

**Pull request merged**
