### PR TITLE
Discard travis output

### PR DESCRIPTION
**Pull request by kamicut**
Redirects travis output to `/dev/null`

### CODE REVIEW

**Comment by kamicut** [comment]
@dalekunce `devseedgit` does not push to this repo, do you know which user does?

**Comment by dalekunce** [comment]
I don't. It might be me :) Is it safe to merge this?

**Comment by kamicut** [comment]
@dalekunce yea, should be safe unless this github token as well was exposed. Do you have a missingmaps bot or do you want to replace the travis.yml file with your encrypted token?

**Comment by kamicut** [comment]
Pinging @smit1678 because I'm not sure how this was set up.

**Comment by dalekunce** [comment]
I should totally create a MM bot account just to make things a little more secure. thanks @kamicut

**Comment by smit1678** [comment]
I support this, thanks @kamicut. We originally had the devseed bot hooked up but then transitioned to @dalekunce.

**Pull request merged**
